spring:
  application:
    name: usuario-service
  h2:
     console: 
        enabled: true
        path: /h2
  datasource: 
      url: jdbc:mysql://localhost:3306/seguridadcurso?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota
      username: root
      password: root_88
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto:  create-drop
        
        
server:
  port: 4567
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
   

  
